### ISSUE TITLE
util.deprecate is not a function

### ISSUE THREAD

**Issue by ekaya97** [sanity-io/document-internationalization#199]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Uncaught error: util.deprecate is not a function
http://localhost:3333/node_modules/.sanity/vite/deps/@sanity_document-internationalization.js?v=f88293dd:3369:174
TypeError: util.deprecate is not a function
    at http://localhost:3333/node_modules/.sanity/vite/deps/@sanity_document-internationalization.js?v=f88293dd:3369:174
    at requireNode2 (http://localhost:3333/node_modules/.sanity/vite/deps/@sanity_document-internationalization.js?v=f88293dd:3501:4)
    at http://localhost:3333/node_modules/.sanity/vite/deps/@sanity_document-internationalization.js?v=f88293dd:3503:150

**To Reproduce**

1. Install and configure document-internationalization as per readme 
2. Run npm run dev
3. Error pops up, studio won't load further

**Expected behavior**

Document internationalization to be available 

**Screenshots**
None necessary

**Which versions of Sanity are you using?**

@sanity/cli (global)                   3.67.1 (latest: 3.68.0)
@sanity/document-internationalization   3.2.1 (up to date)
@sanity/eslint-config-studio            5.0.1 (up to date)
@sanity/vision                         3.67.1 (latest: 3.68.0)
sanity                                 3.67.1 (latest: 3.68.0)

**What operating system are you using?**
macOS Sonoma 14.2.1 (23C71)

**Which versions of Node.js / npm are you running?**
tried
npm info using npm@10.8.2
npm info using node@v20.18.1
and
npm info using npm@10.2.0
npm info using node@v21.1.0
and
npm info using npm@10.9.0
npm info using node@v22.12.0

**Additional context**

requireNode2 function is called, even though sanity is running with vite. The browser check at 
`typeof process > "u" || process.type === "renderer" || process.browser === true || process.__nwjs ? src.exports = requireBrowser$1() : src.exports = requireNode2();`
seems to fail.
Claude says this may be due to debug package. Tried installing debug package and adding 
`vite :{
    resolve: {
      alias: {
        debug: 'debug/src/browser.js'
      }
    }
  }``
to sanity.config.ts - didn't fix with and without this config.

**Security issue?**
no

**Comment by mdillgen** [comment]
Facing the same issue in dev mode only!

**Comment by th-km** [comment]
I'm experiencing the same issue after upgrading to 3.3.0.

**Comment by eldoy** [comment]
Same here:

```
Uncaught error: util.deprecate is not a function
http://localhost:3333/node_modules/.sanity/vite/deps/@sanity_document-internationalization.js?v=a1c0a41d:3395:174
TypeError: util.deprecate is not a function
    at http://localhost:3333/node_modules/.sanity/vite/deps/@sanity_document-internationalization.js?v=a1c0a41d:3395:174
    at requireNode2 (http://localhost:3333/node_modules/.sanity/vite/deps/@sanity_document-internationalization.js?v=a1c0a41d:3527:4)
    at http://localhost:3333/node_modules/.sanity/vite/deps/@sanity_document-internationalization.js?v=a1c0a41d:3529:150
```

**Comment by eldoy** [comment]
Version `3.2.1` is also broken, but `3.2.0` seems to work.

**Comment by h-maina** [comment]
> Version `3.2.1` is also broken, but `3.2.0` seems to work.

Version 3.0.0 is working fine too.

**Comment by sourav-bluup** [comment]
same issue here
